figure(1)
subplot(311)
plot(t,torque(1,:))
hold on
plot(t,tau_cal_list(1,:))
xlabel('time/s')
ylabel('Joint1 Torque/Nm')
subplot(312)
plot(t,torque(2,:))
hold on
plot(t,tau_cal_list(2,:))
xlabel('time/s')
ylabel('Joint2 Torque/Nm')
subplot(313)
plot(t,torque(3,:))
hold on
plot(t,tau_cal_list(3,:))
xlabel('time/s')
ylabel('Joint3 Torque/Nm')
figure(2)
subplot(311)
plot(t,q(1,:),'linewidth',5)
xlabel('time/s')
ylabel('Joint1 Angle/rad')
subplot(312)
plot(t,q(2,:),'linewidth',5)
xlabel('time/s')
ylabel('Joint2 Angle/rad')
subplot(313)
plot(t,q(3,:),'linewidth',5)
xlabel('time/s')
ylabel('Joint3 Angle/rad')
